[tool.poetry]
name = "ordinal-scale-stats"
version = "0.0.1"
description = ""
authors = ["HackerSpace Trójmiasto"]
license = "MIT license"
readme = "README.md"
packages = [{include = "ordinal_scale_stats_py"}]

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
